=============================        수학 함수 (내장함수)

- abs: 절대값
- max: 최댓값
- min: 최솟값
- pow(a, b): 멱승(거듭제곱)
- round(x): 반올림(정수), x.5일 경우 짝수 쪽 정수로 출력
- round(x, n)

In [2]:
round(3.5)

4

In [3]:
round(2.5)

2

In [6]:
round(3.23,1)

3.2

In [7]:
round(3.25,1)

3.2

In [10]:
import numpy as np #numpy 수학함수 사용해 보기

In [9]:
np.log([1, np.e, np.e**2]) # [  0.,   1.,   2., -inf]

array([0., 1., 2.])

In [11]:
np.pi

3.141592653589793

In [12]:
np.e

2.718281828459045

In [13]:
np.sqrt(100) # 10.0

10.0

In [14]:
np.sin(np.pi)

1.2246467991473532e-16

In [15]:
from scipy.special import factorial

arr = np.array([3, 4, 5])
arr

array([3, 4, 5])

In [21]:
a=factorial(arr, exact=False)
a

In [29]:
c=factorial(arr, exact=True)
b

array([  6.,  24., 120.])

In [23]:
arr=[3,4,5]
print(type(arr))

<class 'list'>


In [24]:
b=factorial(arr)

In [25]:
a==b

array([ True,  True,  True])

In [26]:
a is b

False

In [28]:
a==c

array([ True,  True,  True])

In [30]:
# =============================        수학 함수 (import math)
#  math 기본 수학힘수 목록
import math as ma


In [31]:
# 행렬 곱: @
x = np.matrix([[1,2], [3,4]])
print("x = \n", x)
y = np.matrix([[0,1], [1,0]])
print("y = \n", y)
print("x @ y = \n", x @ y)

x = 
 [[1 2]
 [3 4]]
y = 
 [[0 1]
 [1 0]]
x @ y = 
 [[2 1]
 [4 3]]


In [32]:
np.matmul(x, y) # 행렬 곱

matrix([[2, 1],
        [4, 3]])

In [33]:
np.multiply(x, y) # 원소별 곱(elementwise product)

matrix([[0, 2],
        [3, 0]])